# text = "CellBackground"
# use_thin_strokes = true

import = ["~/.config/alacritty/solarized_dark.toml"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[env]
TERM = "alacritty"

[font]
size = 24.0

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 4
y = 0
