#!/usr/bin/env zsh
############################
# This script creates symlinks from the home directory to any desired dotfiles in $HOME/dotfiles
# And also installs applies MacOS defaults I prefer
# And also installs Homebrew Packages and Casks (Apps)
# And also sets up VS Code
############################

set -e

# for i in bash tmux alacritty neofetch rectangle starship wallpaper bin; do
#   cd $i && ./setup
#   cd -
# done

# Need to create base directory for housing symlinks and scripts (.config)
config_dir="$HOME/.config"

if [ ! -d "$config_dir" ]; then
  echo "$config_dir" does not exist.
  echo Creating "$config_dir"
  mkdir -v "$config_dir"
fi

# Are we in the dotfiles directory?
cd "${HOME}"/dotfiles

# Make magic happen
for i in macos wallpaper homebrew zsh zap neofetch alacritty rectangle; do
  echo "$HOME/dotfiles/$i/setup.sh"
  source "$HOME/dotfiles/$i/setup.sh"
  # cd $i && ./setup.sh
  # cd -
done

# INSTALL APPS
# Install Apps using Homebrew & mas
echo "Installing apps using Homebrew and mas"
brew bundle --file="${HOME}"/.config/homebrew/Brewfile
