#!/bin/sh

wallpaper_dir="$HOME/.config/wallpaper"

if [ ! -d "$wallpaper_dir" ]; then
  echo "$wallpaper_dir" does not exist.
  echo Creating "$wallpaper_dir"
  mkdir "$wallpaper_dir"
fi

cp "$PWD/african_sunset.jpeg" "$HOME/.config/wallpaper"

# Get the absolute path to the image
IMAGE_PATH="${HOME}/.config/wallpaper/african_sunset.jpeg"

# AppleScript command to set the desktop background
# osascript <<EOF
# tell application "System Events"
#     set desktopCount to count of desktops
#     repeat with desktopNumber from 1 to desktopCount
#         tell desktop desktopNumber
#             set picture to "$IMAGE_PATH"
#         end tell
#     end repeat
# end tell
# EOF

osascript <<EOF
tell application "System Events"
    tell every desktop
        set picture to "$IMAGE_PATH"
    end tell
end tell
EOF
